In [1]:
import numpy as np

In [2]:
my_list = [10, 20, 30 ,40]

my_array = np.array(my_list)
print(my_array)
print(type(my_array)) #Has already been transformed into an array

[10 20 30 40]
<class 'numpy.ndarray'>


In [4]:
#2D Multidimensional list

my_list = [[1,2,3],[4,5,6],[7,8,9]]
print(my_list)

my_matrix = np.array(my_list)
print(my_matrix) 

#For data preparation

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#Built-in Methods

#np.aragne(start num, end num, interval)
print(np.arange(20))
print(np.arange(2,20,2))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14 16 18]


In [ ]:
print(np.zeros(3)

In [ ]:
#Randomization of Numbers

#random.rand
#randomrandn
#random.randint
#random.normal

In [ ]:
#rand 
print(np.random.rand(3))
print("----")
print(np.random.

In [ ]:
#randint

print(np.random.randint(!000))
print("---")
print(np.random.randint(1,10))


In [ ]:
#normal

print(np.random.normal(165,5,10))

Batch Grading Demo

In [7]:
raw_scores = np.random.normal(85,3,200)
print(raw_scores)

[88.62538761 86.95541131 83.88050389 85.99766114 87.85207708 81.61264569
 84.79098113 86.53363626 88.70999503 83.91791458 84.1651418  85.43538772
 83.31134371 78.80028354 82.5956471  86.47696945 85.21349352 85.31565397
 86.13048315 87.02472352 89.42765751 88.02230687 77.59042718 85.91015064
 86.14763943 90.26110022 86.5943647  83.32784267 80.2371108  87.33176495
 81.03283404 81.21897626 88.79134216 87.7984188  77.30271345 85.81079075
 84.38126965 83.75655123 85.44078877 84.37301631 87.29874497 85.28194136
 88.26075756 85.29811165 76.01299438 85.64613931 90.74436673 86.39902099
 83.34071434 85.34978853 91.16871754 85.85326521 86.05467655 85.91634847
 85.91694467 79.90129977 84.98276792 86.44846206 84.20887389 85.43075688
 83.39036336 85.09670133 85.22790939 86.97080641 86.01662635 86.82949006
 84.53896795 85.61996071 81.56451555 81.99691669 81.3027043  85.90467336
 85.76560641 83.25671261 83.34885283 82.8448405  85.55409062 82.14856738
 84.48244026 88.22217055 82.55781372 84.66872435 82

In [11]:
#Dermine who passe dor failed

passing_score = 80
print(raw_scores >= passing_score)
print(raw_scores[raw_scores <= passing_score])


[ True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  T

In [ ]:
def get_letter_grade() 
    

In [ ]:
vfunc = np.vectorize(get_letter_grade)